[tool.ruff]
line-length = 100
target-version = "py310"

exclude = [
    "build",         # Ignore the 'build' directory
    "dist",          # Ignore the 'dist' directory
    "__pycache__",   # Ignore Python's cache directories
    "notebooks"
]