name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
          python3 -m pip install .[all]

      - name: Build documentation
        run: |
          cd docs && make clean && make html SPHINXOPTS="-D sphinx_gallery_conf.plot_gallery=False"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}  # SSH deploy key for authentication
          external_repository: torch-ttt/torch-ttt.github.io
          publish_branch: main  # GitHub Pages repository should serve from main
          publish_dir: docs/_build/html
