name: tests

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
          python3 -m pip install .[all]
          python3 -m pip install pytest

      - name: Run tests
        run: |
          pytest tests/
