name: weekly paper update

on:
  schedule:
    - cron: '0 8 * * 1'  # Runs every Monday at 08:00 UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-papers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly
          pip install PyYAML

      - name: Run update_papers.py
        run: python update_papers.py
        working-directory: docs/scripts

      - name: Run generate_papers_table.py
        run: python generate_papers_table.py
        working-directory: docs/scripts

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/scripts/data/papers_with_citations.yaml docs/scripts/data/papers_table.html
          git commit -m "Update papers citation data [auto]" || echo "No changes to commit"
          git push
